name: Login to Docker Hub

description: A GitHub Action to login to Docker Hub

inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true
  file:
    description: “Path to the Dockerfile to build”
    required: true
  platforms:
    description: “Platforms to build for”
    required: true
  image_name:
    description: “Name of the image to push”
    required: true
  image_tag:
    description: “Tag of the image to push”
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        file:  ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: |
          ${{ inputs.image_name }}:latest
          ${{ inputs.image_name }}:${{ inputs.image_tag }}
        cache-from: type=registry,ref=${{ inputs.image_name }}:buildcache
        cache-to: type=registry,ref=${{ inputs.image_name }}:buildcache,mode=max
