name: Build images

on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet?
        default: Allen

env:
  APP_VERSION: 0.1.22

jobs:
  get-approval:
    name: Get approval
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Just get approval
        run: echo "Just get approval"

  build-laravel-octane-image:
    needs: get-approval
    name: Start to build laravel octane image and publish to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build laravel octane image and publish to docker hub
        uses: ./.github/actions/publish-to-docker-hub
        with:
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          file: dockerfiles/Dockerfile.app
          platforms: linux/amd64, linux/arm64
          image_name: nella0128/docfunc-app
          image_tag: ${{ env.APP_VERSION }}

  build-laravel-horizon-image:
    needs: get-approval
    name: Start to build laravel horizon image and publish to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push laravel horizon
        uses: ./.github/actions/publish-to-docker-hub
        with:
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          file: dockerfiles/Dockerfile.horizon
          platforms: linux/amd64, linux/arm64
          image_name: nella0128/docfunc-horizon
          image_tag: ${{ env.APP_VERSION }}

  build-laravel-scheduler-image:
    needs: get-approval
    name: Start to build laravel scheduler image and publish to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push laravel horizon
        uses: ./.github/actions/publish-to-docker-hub
        with:
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          file: dockerfiles/Dockerfile.scheduler
          platforms: linux/amd64, linux/arm64
          image_name: nella0128/docfunc-scheduler
          image_tag: ${{ env.APP_VERSION }}

  build-aws-mysql-client-image:
    needs: get-approval
    name: Start to build aws mysql client image and publish to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push laravel horizon
        uses: ./.github/actions/publish-to-docker-hub
        with:
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          file: dockerfiles/Dockerfile.aws-mysql-client
          platforms: linux/amd64, linux/arm64
          image_name: nella0128/aws-mysql-client
          image_tag: ${{ env.APP_VERSION }}
