name: build-container

on:
  workflow_run:
    workflows:
      - tests
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Display directory structure
        run: |
          echo "Directory structure:"
          find . -type d

      - name: Build and push laravel octane
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/Dockerfile.app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docfunc-app:latest

      - name: Build and push laravel horizon
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/Dockerfile.horizon
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docfunc-horizon:latest

      - name: Build and push laravel scheduler
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/Dockerfile.scheduler
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docfunc-scheduler:latest
