on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: blog_tests
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare aplication
        env:
          LARAVEL_TEST_ENV: ${{ secrets.LARAVEL_TEST_ENV }}
        run: |
          printf "%s" "$LARAVEL_TEST_ENV" > .env
          php artisan key:generate

      - name: Run unit test
        run: vendor/bin/phpunit tests/
