name: CD
on:
  workflow_run:
    workflows: [ CI ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            sudo supervisorctl stop all
            sudo service mysql stop
            sudo service redis stop
            cd /var/www/html/blog
            sudo -u www-data git pull --ff-only
            sudo -u www-data composer install --no-progress --prefer-dist --optimize-autoloader --no-dev
            sudo -u www-data npm install
            sudo -u www-data npm run production
            sudo -u www-data php artisan view:cache
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo service mysql start
            sudo service redis start
            sudo supervisorctl start all
