name: Destroy AWS Lambda

on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        default: Allen

permissions:
  id-token: write
  contents: read

jobs:
  destroy-lambda:
    name: Destroy aws lambda
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure php 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - name: Install php packages
        run: composer install --prefer-dist --optimize-autoloader --no-dev

      - name: Set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install javascript packages and build the frontend assets
        run: |
          npm install

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::154471991214:role/github_action
          aws-region: us-west-2

      - name: Destroy aws lambda
        run: |
          npm install serverless serverless-lift
          node_modules/.bin/serverless remove --stage production
